---
- hosts: controller
  roles:
  - controller

- hosts: computes
  roles:
  - computes

- hosts: controller
  roles:
  - post_install

- hosts: monitoring
  vars:
    openjdk_version: "openjdk-11-jdk"
    kafka_url: "https://archive.apache.org/dist/kafka/2.2.0/kafka_2.12-2.2.0.tgz"
    kafdrop_bin_url: "https://bintray.com/obsidiandynamics/kafdrop/download_file?file_path=com%2Fobsidiandynamics%2Fkafdrop%2Fkafdrop%2F3.8.1%2Fkafdrop-3.8.1.jar"
    grafana_version: "{{ GRAFANA_RELEASE }}"
    grafana_security:
      admin_user: admin
      admin_password: "{{ ADMIN_PASSWORD }}"
    grafana_provisioning_synced: true
    grafana_datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        database: ni
        url: 'http://{{ INFLUXDB_SERVER_ADDR }}:8086'
    docker_users: ["{{ ansible_user }}"]
    graylog_port: 9001
    graylog_rsyslog_port: 1514
    rsyslog_listen_port: 10514
    graylog_host_addr: "{{ inventory_hostname }}"
  roles:
  - firewall
  - role: influxdb
    become: true
  - java
  - kafka
  - kafdrop
  - role: grafana
    tags: grafana
  - logcenter
  - graylog
  tasks:
  - name: "config rsyslog"
    with_items: [ni_collector, ni_mon, ni_nfvo]
    include_role:
      name: rsyslog
    vars:
      RSYSLOG_SERVICE_ID: "{{ item }}"
  - name: "install and config ni_mano services"
    with_items: [ni_collector, ni_mon, ni_nfvo]
    include_role:
      name: ni_mano
      apply:
        tags: ni_mano, "{{ item }}"
    vars:
      SERVICE_MODULE: "{{ item }}"
    tags: ni_mano, ni_collector, ni_mon, ni_nfvo

- hosts: controller
  roles:
  - ni_horizon

- hosts: computes
  tasks:
  - name: "install collectd if monitoring host exist"
    import_role:
      name: collectd
    when: "'monitoring' in groups"

- hosts: monitoring
  roles:
  - ni_tests
